#!/bin/bash
g="${b}\033[1;30m"
b="\033[0m"
b1="$b\033[1;37m"
r="${b}\033[1;31m"
r1="${b}\033[31m"
A="${b}\033[1;34m"
A1="${b}\033[34m"
ac="${b}\e[1;36m"
ac1="${b}\e[36m"
v="${b}\033[1;32m"
v1="${b}\033[32m"
m="$b\033[1;35m"
m1="$b\033[35m"
a="$b\033[1;33m"
a1="$b\033[33m"
cy="$b\033[38;2;23;147;209m"
command -v proot > /dev/null 2>&1 || { sleep 0.5; echo >&2 -e "\n$v1[$b1*$v1]$b Instalando proot..."; pkg install proot -y &>> /dev/null;sleep 0.5;}
trap Adios INT
Adios() {
	echo
	printf "$A[$b1+$A]${b1} Creador:$a     Anonymous Zpt\n"
	printf "$A[$b1+$A]${b1} Herramienta:$a T-root\n"
	printf "$A[$b1+$A]${b1} GitHub:$a      https://github.com/JoseZpt\n"
	printf "$A[$b1+$A]${b1} YouTube:$a     http://www.youtube.com/c/Anonymous$b\n"
	echo
	exit
}
banner1() {
	clear;sleep 0.5
	printf "$g"
	echo '                      :::!~!!!!!:.'
	echo '                  .xUHWH!! !!?M88WHX:.'
	echo '                .X*#M@$!!  !X!M$$$$$$WWx:.'
	echo '               :!!!!!!?H! :!$!$$$$$$$$$$8X:'
	echo '              !!~  ~:~!! :~!$!#$$$$$$$$$$8X:'
	echo '             :!~::!H!<   ~.U$X!?R$$$$$$$$MM!'
	echo '             ~!~!!!!~~ .:XW$$$U!!?$$$$$$RMM!'
	echo '               !:~~~ .:!M"T#$$$$WX??#MRRMMM!'
	echo '               ~?WuxiW*`   `"#$$$$8!!!!??!!!'
	echo -e '             :X- M$$$$ '$r'   *'$g'  `"T#$T~!8$WUXU~'
	echo '            :%`  ~#$$$m:        ~!~ ?$$$$$$'
	echo '          :!`.-   ~T$$$$8xx.  .xWW- ~""##*""'
	echo -e '.....   -~~:<` !    ~?T#$$@@W@*?$$ '$r'  *'$g'  /`'
	echo 'W$@@M!!! .!~~ !!     .:XUW$W!~ `"~:    :'
	echo '#"~~`.:x%`!!  !H:   !WM$$$$Ti.: .!WUn+!`'
	echo ':::~:!!`:X~ .: ?H.!u "$$$B$$$!W:U!T$$M~'
	echo '.~~   :X@!.-~   ?@WTWo("*$$$W$TH$! `'
	echo 'Wi.~!X$?!-~    : ?$$$B$Wu("**$RM!'
	echo '$R@i.~~ !     :   ~$$$$$B$$en:``'
	echo '?MXT@Wx.~    :     ~"##*$$$$M~'
	echo
	sleep 0.9
	printf "$A[$b1+$A]${b1} Creador:$a     Anonymous Zpt\n"
	sleep 0.4
	printf "$A[$b1+$A]${b1} Herramienta:$a T-root\n"
	sleep 0.4
	printf "$A[$b1+$A]${b1} GitHub:$a      https://github.com/Anonymous-Zpt\n"
	sleep 0.4
	printf "$A[$b1+$A]${b1} YouTube:$a     http://www.youtube.com/c/AnonymousZpt$b\n"
	sleep 4
}
banner1
echo -e "${g}Comenzando Proceso Root .."
sleep 2
ruta=$PREFIX/bin
if [[ -e $ruta/root ]]; then
	rm $ruta/root
fi
touch $ruta/root
echo "proot -0 -w ~ $PREFIX/bin/bash" >> $ruta/root
chmod 700 $ruta/root
echo
sleep 5
clear
echo -e "$v"
echo -e ' ________\n< T-root >\n --------\n        \   ^__^\n         \  (xx)\_______\n            (__)\       )\/\\\n             U  ||----w||\n                ||     ||\n  \033[0m'
echo
sleep 0.3
printf "$A[$b1+$A]${b1} Proceso:$a     Finalizado\n"
sleep 0.3
printf "$A[$b1+$A]${b1} Creador:$a     Anonymous Zpt\n"
sleep 0.3
printf "$A[$b1+$A]${b1} Herramienta:$a T-root\n"
sleep 0.3
printf "$A[$b1+$A]${b1} GitHub:$a      https://github.com/Anonymous-Zpt\n"
sleep 0.3
printf "$A[$b1+$A]${b1} YouTube:$a     http://www.youtube.com/c/AnonnymousZpt$b\n"
sleep 0.3
printf "$A[$b1+$A]${b1} Activacion:$a  Para Activar Root Utiliza La Palabra$r root$b\n"
echo
